### ISSUE TITLE
found bug when running uglify

### ISSUE THREAD

**Issue by winkidney** [Treri/me-pageloading#3]
angulr's dependencies has been broken by this behavior.

**Comment by ik0r** [comment]
?? @winkidney

**Comment by winkidney** [comment]
When i use gulp, uglify for compress and combine all js files(refs to angular-gulp-generator) to build, the browser will give me some error like "Dependency lost", the dependencies names that "me-pageloading" need will be short-form (like "q, z, j").
It is what uglify do.
Angular inject all dependencies by its name, but short-name like "q, z" will not be resolved.
Refs to http://thegreenpizza.github.io/2013/05/25/building-minification-safe-angular.js-applications/

···
var myController = function(anyVariableName, $http) {
  //We included $scope and the $http service into our controller.
  //Since we set up the $inject attribute on our controller, it doesn't matter what variable names we use.
}

myController.$inject = ['$scope', '$http']
···

**Comment by winkidney** [comment]
I will send an pull request later:)

**Comment by ik0r** [comment]
@winkidney does min.js work?

I have used `['$inject1', '$inejct2', function($inject1, $inject2){}]` syntax to avoid uglify error in everywhere possiable and my demo `angular-ui-router.html` also used the uglified file. No errors

**Comment by winkidney** [comment]
Ok，Maybe it's my fault?I will test it in another environment: ) and then send you a traceback

**Comment by ik0r** [comment]
thanks

**Comment by ik0r** [comment]
No further comments, closed.

Feel free to reopen this issue if you have plobrems

**Comment by winkidney** [comment]
I'm sorry for that:)
I can not reproduce the problem, thanks for your patience.

2016-03-12 10:56 GMT+08:00 Treri Liu notifications@github.com:
